Repository damoang/theme, pull requests merged in 2024-05, with the labels that each got.

#169 feat: 글 목록에서 회원만 보기 아이콘을 "회원" 글자로 표시해 제목 앞으로 이동
  skin/board/free/list/list/list.skin.php
Labels: enhancement

#168 댓글 이미지 썸네일 생성
  skin/board/basic/comment/basic/comment.skin.php
  skin/board/free/comment/basic/comment.skin.php
Labels: enhancement, optimization

#165 Custom UI 자기소개 링크 수정에 따른 mb_id 추출 방식 변경
  layout/basic/js/customui.js
Labels: bug

#161 이모티콘 정적로직 적용
  app/clip.emo.php
Labels: optimization

#160 자동저장글 삭제시 버그 수정
  js/autosave.js
Labels: bug

#172 feat: 메인 추천글 위젯에 추천 수 표시 추가
  layout/basic/widget/wr-list-recommend/widget.php
Labels: enhancement

#171 feat: 공지사항 감추기 버튼을 공지사항이 있을 때만 표시하도록 변경
  skin/board/basic/category/basic/category.skin.php
  skin/board/free/category/basic/category.skin.php
Labels: enhancement

#170 fix: jquery 초기화 타이밍 문제 고침
  layout/basic/js/custom_features.js
Labels: bug

#175 fix: 공지사항 버튼 감추기로 인해 모바일에서 다른 항목들의 위치 문제 고침
  skin/board/free/category/basic/category.skin.php
Labels: bug

#174 제목영역 레이아웃 정리 및 툴팁 적용
  layout/basic/css/style.css
  skin/board/basic/list/list-sm/list.skin.php
  skin/board/basic/list/list/list.skin.php
  skin/board/basic/list/list_admin/list.skin.php
  skin/board/basic/list/list_trueroom/list.skin.php
  skin/board/free/list/list-sm/list.skin.php
  skin/board/free/list/list/list.skin.php
  skin/board/free/list/list_admin/list.skin.php
  skin/board/free/list/list_trueroom/list.skin.php
Labels: enhancement

#187 게시판 스킨 병합 및 미리보기 기능 제거
  app/board.skin.php
  js/nariya.js
  layout/basic/_head.sub.php
  layout/basic/component/member.offcanvas.php
  layout/basic/js/customui.js
  layout/basic/widget/wr-gallery/widget.php
  layout/basic/widget/wr-list-recommend/widget.php
  layout/basic/widget/wr-list/widget.php
  layout/basic/widget/wr-webzine/widget.php
  skin/board/basic/list.skin.php
  skin/board/basic/list/gallery-sm/list.skin.php
  skin/board/basic/list/gallery/list.skin.php
  skin/board/basic/list/list-sm/list.skin.php
  skin/board/basic/list/list/list.skin.php
  skin/board/basic/list/list_admin/list.skin.php
  skin/board/basic/list/list_trueroom/list.skin.php
  skin/board/basic/list/webzine/list.skin.php
  skin/board/basic/view.skin.php
  skin/board/basic/view/basic/view.skin.php
  skin/board/basic/view/free/view.skin.php
  skin/board/basic/view/true/view.skin.php
  skin/board/basic/write.skin.php
  skin/board/basic/write_update.head.skin.php
  skin/board/free/list/gallery-sm/list.skin.php
  skin/board/free/list/gallery/list.skin.php
  skin/board/free/list/webzine/list.skin.php
  skin/member/basic/register_form.skin.php
Labels: enhancement, optimization

#195 Custom UI - 읽은 글 기록 및 활용 기능 추가.
  layout/basic/component/member.offcanvas-customui.php
  layout/basic/js/customui.js
Labels: enhancement

#213 그룹페이지에서 소모임용 위젯 배치
  layout/basic/group.php
  layout/basic/widget/wr-list-recommend/widget.php
  layout/basic/widget/wr-list/widget.php
Labels: enhancement

#217 feat: 테마를 지정할 때 스킨설정을 적용
  readme.txt
  theme.config.php
Labels: enhancement

#223 사이드바 메뉴의 아이콘, 단축키 표시를 정렬
  layout/basic/component/menu.offcanvas.php
  layout/basic/component/sidebar.php
  layout/basic/css/style.css
  layout/basic/inc.menu.php
  layout/basic/js/customui.js
Labels: enhancement

#226 메인페이지에서 푸터가 깨지는 문제 수정 및 UI 개선
  layout/basic/index.php
  layout/basic/tail.php
Labels: enhancement

#224 feat: 글 목록에서 블록 링크가 체크박스 등의 UI와 상호작용을 방해하는 문제 고침
  layout/basic/css/style.css
Labels: bug, enhancement

#225 새 알림이 있을 때 toast 대신 헤더 영역에 아이콘에 표시하도록 변경
  layout/basic/component/noti.offcanvas.php
  layout/basic/head.php
  layout/basic/tail.php
Labels: enhancement

#227 fix: 알림 아이콘이 비로그인 상태에서 표시되는 문제 고침
  layout/basic/head.php
Labels: bug

#228 메인, 게시판목록 추천수 컬러세트 지정 및 노출 위치 수정
  layout/basic/css/style.css
  layout/basic/widget/wr-list-recommend/widget.php
  skin/board/basic/list/list/list.skin.php
Labels: enhancement
